export function TermsPage() {
  return (
    <div className="prose prose-sm mx-auto max-w-3xl dark:prose-invert">
      <h1>Terms of Service</h1>
      <p className="text-muted-foreground"><em>Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</em></p>

      <h2>1. Acceptance</h2>
      <p>By using PokeGrails, you agree to these terms. If you do not agree, do not use the service.</p>

      <h2>2. Service Description</h2>
      <p>PokeGrails provides AI-powered analytics and pricing data for Pokémon Trading Card Game collectibles. The service is for informational purposes only and does not constitute financial or investment advice.</p>

      <h2>3. Accounts</h2>
      <ul>
        <li>You must provide accurate information when creating an account</li>
        <li>You are responsible for maintaining the security of your account</li>
        <li>One account per person; sharing accounts is not permitted</li>
        <li>We reserve the right to suspend accounts that violate these terms</li>
      </ul>

      <h2>4. Subscriptions & Payments</h2>
      <p>Premium features require a paid subscription processed through Stripe. Subscriptions renew automatically unless cancelled. Refunds are handled on a case-by-case basis.</p>

      <h2>5. Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Scrape, crawl, or automate access to the service</li>
        <li>Attempt to bypass rate limits or access controls</li>
        <li>Reverse-engineer the analytics models</li>
        <li>Use the service for any illegal purpose</li>
        <li>Redistribute premium data or analytics to non-subscribers</li>
      </ul>

      <h2>6. Disclaimer</h2>
      <p><strong>PokeGrails is not a financial advisor.</strong> All price predictions, valuations, and investment signals are generated by statistical models and may be inaccurate. Past performance does not guarantee future results. You are solely responsible for your buying and selling decisions.</p>

      <h2>7. Limitation of Liability</h2>
      <p>PokeGrails is provided "as is" without warranties. We are not liable for any losses arising from reliance on the information provided by the service.</p>

      <h2>8. Changes</h2>
      <p>We may modify these terms at any time. Continued use after changes constitutes acceptance.</p>

      <h2>9. Contact</h2>
      <p>Questions about these terms can be directed to <a href="mailto:support@pokegrails.com">support@pokegrails.com</a>.</p>
    </div>
  )
}
