export type HelpSection = {
  id: string
  page: string
  title: string
  summary: string
  details: string[]
}

export const HELP_SECTIONS: HelpSection[] = [
  {
    id: 'dashboard-overview',
    page: 'Dashboard',
    title: 'Dashboard overview',
    summary: 'High-level snapshot of model, pricing, and opportunity signals.',
    details: [
      'Dashboard cards and charts read from /api/dashboard, /api/cards, /api/sets, and /api/upcoming.',
      'All chart filters are local UI preferences only; they do not retrain or modify backend model outputs.',
      'Use this page to identify where to drill deeper into Cards, Buy Signals, and Sets.',
    ],
  },
  {
    id: 'dashboard-chart-panel',
    page: 'Dashboard',
    title: 'Chart panel and tabs',
    summary: 'Interactive charts that switch among pull-demand, fair-market, deal mix, and set ranking.',
    details: [
      'Pull vs demand: x = pull_cost_score, y = desirability_score, bubble size ~ price scale.',
      'Price reality check: x = market_price, y = predicted_price. Points below diagonal are below model fair.',
      'Deal mix bins positive discount where discount = ((fair - market) / fair) * 100.',
      'Sets with deals counts cards in each set with discount >= your minimum deal threshold.',
    ],
  },
  {
    id: 'dashboard-social-momentum',
    page: 'Dashboard',
    title: 'Social momentum',
    summary: 'Ranks cards by blended social activity signal — Reddit buzz and Google Trends.',
    details: [
      'Momentum score (0–100) blends Reddit buzz and Google Trends data. When Reddit mentions are sparse, Google Trends is weighted more heavily.',
      'The bar under each card name shows relative momentum strength compared to the top card in the list. A full bar means this is the highest-momentum card.',
      'The number to the right (e.g. "74/100") is the card\'s absolute momentum score on a 0–100 scale.',
      'Rows are deduplicated by character family so one character does not dominate multiple slots.',
      'Higher momentum indicates growing social attention but does not guarantee value — pair with fair-vs-market analysis and set context before acting.',
    ],
  },
  {
    id: 'dashboard-model-pipeline',
    page: 'Dashboard',
    title: 'Model pipeline',
    summary: 'Coverage diagnostics for ingestion, market pricing, model scoring, and social enrichment.',
    details: [
      'Shows counts with market prices, model predictions, and social signals currently available.',
      'Valuation chips summarize UNDERVALUED / FAIR / OVERVALUED distribution from valuation_flag.',
      'If coverage is low, run ingest/refresh before acting on outputs.',
    ],
  },
  {
    id: 'cards-overview',
    page: 'Cards',
    title: 'Cards page overview',
    summary: 'Main card explorer with sorting, filtering, trend, and deep model detail.',
    details: [
      'Filters combine name, set, print bucket, valuation flag, and sort order.',
      'Column chooser controls visibility only; no backend impact.',
      'Open a row to view full fair-value breakdown, trend chart, AI view, and buy links.',
    ],
  },
  {
    id: 'cards-model-fair',
    page: 'Cards',
    title: 'Model fair and valuation math',
    summary: 'How fair value and gap metrics are calculated.',
    details: [
      'Model fair is a heuristic estimate (pull/desirability + anchoring), not a guaranteed market quote.',
      'Dollar gap uses market - fair. Negative gap means market is below model fair (possible deal).',
      'Relative spread is normalized by the larger absolute price to avoid tiny-price distortion.',
    ],
  },
  {
    id: 'cards-30d-trend',
    page: 'Cards',
    title: '30d trend sparkline',
    summary: 'Small chart summarizing recent price movement.',
    details: [
      'Sparkline uses up to 31 latest points from price history.',
      'Price point source uses tcgplayer_market when present, otherwise pricecharting_median fallback.',
      'Displayed % is computed from first to last point in the sparkline window.',
    ],
  },
  {
    id: 'cards-detail-sheet',
    page: 'Cards',
    title: 'Card detail sheet',
    summary: 'Expanded view for one card with calculations and negotiation guidance.',
    details: [
      'Shows pull/desire, model fair, market, adjusted condition view, and optional explain_json details.',
      'AI investment section displays composite score and its signal components.',
      'Negotiation values are generated heuristics and should be treated as guidance bands.',
    ],
  },
  {
    id: 'cards-psa-roi',
    page: 'Cards',
    title: 'PSA ROI estimator',
    summary: 'Quick grading outcome estimate from raw price assumptions.',
    details: [
      'Estimated graded value uses fixed multipliers (PSA 9 ~1.6x, PSA 10 ~2.4x).',
      'ROI formula: ((estimatedGraded - gradingCost - rawPrice) / rawPrice) * 100.',
      'This is a rough scenario tool and excludes fees, shipping, and variance.',
    ],
  },
  {
    id: 'sets-overview',
    page: 'Sets',
    title: 'Sets page and verdicts',
    summary: 'Compares sealed product economics versus buying singles.',
    details: [
      'Verdicts classify each set as rip packs, rip with caution, buy singles, hold sealed, or break-even.',
      'EV ratio is EV per product divided by product price, shown as a percentage.',
      'Confidence icons reflect quantity/quality of price sources used.',
    ],
  },
  {
    id: 'sets-opportunity-map',
    page: 'Sets',
    title: 'Set opportunity map',
    summary: 'Scatter map positioning sets by chase intensity and EV ratio.',
    details: [
      'X-axis: chase score. Y-axis: EV / box price.',
      'Dot size scales with set size (card count). Color reflects verdict class.',
      'Use selection and hover to inspect details, then click through to set cards.',
    ],
  },
  {
    id: 'signals-overview',
    page: 'Buy Signals',
    title: 'Buy signals overview',
    summary: 'Cards currently flagged undervalued by model criteria.',
    details: [
      'Discount % uses ((fair - market) / fair) * 100 when fair and market are both positive.',
      'Most savings uses absolute dollars (fair - market).',
      'Sort and set filters help prioritize either efficiency (% off) or absolute savings.',
    ],
  },
  {
    id: 'watchlist-overview',
    page: 'Watchlist',
    title: 'Watchlist and alerts',
    summary: 'Track holdings or targets and monitor live market changes.',
    details: [
      'Each row stores quantity, optional purchase price, and optional target buy price.',
      'P&L is (market - purchase_price) * quantity when both prices are available.',
      'Browser push alerts require service worker registration and VAPID configuration.',
    ],
  },
  {
    id: 'alerts-overview',
    page: 'Alerts',
    title: 'Alerts action list',
    summary: 'Filtered high-priority BUY candidates with anomaly guardrails.',
    details: [
      'List is intended for score-qualified BUY-zone candidates from backend rules.',
      'Cards are shown with fair and market context for quick triage.',
      'Use Cards page for detailed validation before acting.',
    ],
  },
  {
    id: 'card-show-overview',
    page: 'Card Show',
    title: 'Card show export',
    summary: 'Offline printable export of top opportunities.',
    details: [
      'Exports a single HTML artifact for printing or event-floor usage.',
      'Includes top undervalued picks, negotiation bands, and QR back to dashboard.',
      'Data reflects latest server snapshot at time of export.',
    ],
  },
  {
    id: 'track-record-overview',
    page: 'Track Record',
    title: 'Track record overview',
    summary: 'Transparent performance tracking — see how the model\'s predictions hold up over time.',
    details: [
      'The Track Record page gives you full transparency into how the model performs. It is organized into four tabs: Overview, Trends, Accuracy Map, and Signals.',
      'The data coverage banner at the top shows the full tracking period, number of snapshots, cards tracked, and total buy signals ever issued.',
      'The Confidence Score (0–100) is a weighted blend: 50% prediction accuracy, 30% buy signal hit rate, and 20% sample size depth. Higher is better.',
      'Prediction Accuracy measures how close the model\'s "fair value" estimate is to actual market prices, calculated as (1 − median absolute error) × 100.',
      'Buy Signal Hit Rate shows what percentage of UNDERVALUED flags led to price increases. Signals need 7+ days before being evaluated.',
      'Data accumulates automatically — the model snapshots predictions daily at midnight and after every refresh (every 4 hours). Over days and weeks, the track record builds a complete picture.',
      'Use this page to gauge how much weight to give the model\'s recommendations and to spot trends in model quality.',
    ],
  },
  {
    id: 'track-record-methodology',
    page: 'Track Record',
    title: 'Methodology and scoring',
    summary: 'How the track record metrics are computed and what the numbers mean.',
    details: [
      'Confidence Score: blends prediction accuracy (50%), signal hit rate (30%), and how many signals have been evaluated (20%). Range 0–100. ≥70 = Excellent, ≥65 = Good, ≥45 = Fair, below = Building.',
      'Prediction Accuracy: for each snapshot day, we compare every card\'s predicted fair value to its actual market price. The metric is (1 − median absolute % error) × 100. Example: 85% accuracy means the median card prediction is within 15% of market.',
      'Buy Signal Hit Rate: a card is flagged UNDERVALUED when market price / predicted fair value < 0.80. We track the market price on the date the flag was first issued and compare to the current market price. "Hit" = price went up. Signals < 7 days old are shown as "active" and excluded from the hit rate calculation.',
      'Average Signal Return: the mean percentage return across all evaluated (7d+) buy signals. Positive means the model\'s buy signals are profitable on average.',
      'The valuation model uses a calibrated multiplicative formula: base × 1.19^pull_cost × 1.41^desirability, then shrinks toward peer tier medians and market anchoring. "OVERVALUED" is flagged when market/predicted > 1.25; "GROWTH BUY" when overvalued but 12-month projection exceeds market by 12%+ with ≥10% annual growth.',
      'Snapshots are taken daily at midnight and after each model refresh cycle (every 4 hours). Each snapshot records every card\'s predicted price, market price, and valuation flag.',
    ],
  },
  {
    id: 'track-record-timeline',
    page: 'Track Record',
    title: 'Prediction error timeline',
    summary: 'How the model\'s prediction error trends over time.',
    details: [
      'Each point on the chart is the median absolute percentage error between predicted fair value and actual market price for that snapshot day.',
      'Lower is better — a value of 10% means the model\'s fair estimate was within 10% of the actual market price, on average (median).',
      'The trend matters more than any single point: a downward trend means the model is improving; an upward trend means market conditions may be shifting.',
      'The chart tooltip also shows how many active buy signals existed on that date, giving context for signal-heavy vs signal-sparse periods.',
      'This chart requires at least 2 daily snapshots to render. Each point represents one day\'s worth of predictions across all tracked cards.',
    ],
  },
  {
    id: 'track-record-hit-rate',
    page: 'Track Record',
    title: 'Signal hit rate timeline',
    summary: 'Cumulative buy signal success rate over time.',
    details: [
      'Hit rate = (signals where price went up) / (total evaluated signals) as of each snapshot date.',
      'A signal is "evaluated" once it has been active for at least 7 days — this gives the market enough time to move.',
      'This chart shows the running (cumulative) hit rate up to each date, so it smooths out as more signals accumulate.',
      'Early on with few signals, the hit rate may be volatile (e.g. 0% or 100%). As more signals are evaluated, the rate stabilizes and becomes more meaningful.',
      'A sustained rate above 50% means the model identifies undervalued cards more often than not.',
    ],
  },
  {
    id: 'analytics-overview',
    page: 'Analytics',
    title: 'Model Status',
    summary: 'Health dashboard for all analytics models — batch and on-demand.',
    details: [
      'Batch models run across the full card catalog on a schedule (every 4 hours) or when an admin triggers a manual refresh.',
      'On-demand models analyze a single card instantly — search for any card to run momentum, supply shock, and cointegration checks.',
      'Each model card shows last-run time, card coverage, and current status (ready, running, or stale).',
      'Use "Run All Models" to recompute every batch model in sequence. Progress and timing are shown live.',
    ],
  },
  {
    id: 'analytics-momentum',
    page: 'Analytics',
    title: 'Momentum Watch',
    summary: 'Cards showing accelerating price patterns that may precede significant moves.',
    details: [
      'Momentum score (0–100) measures recent price acceleration using 30-day and 7-day price slopes, volume proxies, and trend consistency.',
      'Cards scoring 75+ are highlighted with a ring — these are showing the strongest acceleration signals.',
      'The percentage change shown is the trailing 30-day price movement. Trend direction (e.g. "accelerating", "decelerating") provides additional context.',
      'Momentum is a timing signal, not a value signal — a card can have high momentum but still be overvalued. Cross-reference with fair value.',
    ],
  },
  {
    id: 'analytics-insights',
    page: 'Analytics',
    title: 'Market Intelligence',
    summary: 'Which card features drive the model\'s price predictions.',
    details: [
      'Feature importance is computed from a gradient-boosted decision tree trained on all scored cards.',
      'Bar lengths show relative importance (0–100%). Higher bars mean the model relies more heavily on that feature for price predictions.',
      'Common top features include rarity, desirability score, pull cost, set age, and market liquidity.',
      'Use this to understand what the model "thinks" matters — it can surface non-obvious drivers like character premium or set lifecycle stage.',
    ],
  },
  {
    id: 'analytics-anomalies',
    page: 'Analytics',
    title: 'Market Events',
    summary: 'Unusual price movements detected by statistical anomaly analysis.',
    details: [
      'Anomalies are flagged when a card\'s recent price movement exceeds what is statistically expected based on its historical volatility.',
      'Alert levels (info, warning, critical) reflect the magnitude of the deviation — critical events are rare and worth investigating.',
      'The price trend percentage shows the move that triggered the anomaly. Explanation text provides context on what was detected.',
      'Not every anomaly is actionable — data lag, listing errors, and low-volume cards can produce false positives.',
    ],
  },
  {
    id: 'analytics-clusters',
    page: 'Analytics',
    title: 'Archetypes',
    summary: 'Cards grouped into market archetypes using k-means clustering.',
    details: [
      'Clustering uses k-means on normalized card features (price, pull cost, desirability, rarity tier, set age) to find natural groupings.',
      'Each archetype has a name, color, and profile describing its typical characteristics (e.g. "chase ultra-rares", "bulk commons").',
      'The pie chart shows the distribution of cards across archetypes. Hover for counts and percentages.',
      'Use archetypes to understand market segments — different archetypes respond differently to trends and set releases.',
    ],
  },
  {
    id: 'analytics-supply',
    page: 'Analytics',
    title: 'Supply Warnings',
    summary: 'Cards showing potential supply-demand imbalances.',
    details: [
      'Supply shock detection compares price momentum, listing volume proxies, and historical volatility to flag cards where supply may be tightening.',
      'Alert levels indicate severity. A "critical" alert with rising prices and falling supply proxies suggests the card may become harder to find at current prices.',
      'The supply proxy metric is a heuristic estimate — it uses price volatility and listing frequency patterns, not direct inventory counts.',
      'These warnings are most useful for cards you are actively watching or holding — they can signal when to buy before prices climb.',
    ],
  },
  {
    id: 'analytics-correlations',
    page: 'Analytics',
    title: 'Correlated Movers',
    summary: 'Card pairs whose prices move together over time.',
    details: [
      'Cointegration analysis identifies pairs of cards with statistically linked price movements — when one moves, the other tends to follow.',
      'Correlation strength is shown as a percentage. Higher values mean tighter linkage. Only pairs above a significance threshold are shown.',
      'Common causes include same-character cards across sets, same-rarity cards in the same set, or cards popular in the same deck archetype.',
      'Use this for portfolio diversification — holding highly correlated cards means concentrated risk. Or use it to anticipate moves in one card based on another.',
    ],
  },
  {
    id: 'analytics-pca',
    page: 'Analytics',
    title: 'Variance Analysis',
    summary: 'Principal Component Analysis revealing the main axes of price variation.',
    details: [
      'PCA (Principal Component Analysis) reduces the many card features into a few "principal components" that capture the most price variation.',
      'Each component explains a percentage of total variance. The first few components typically capture 60–80% of all variation in the market.',
      'The cumulative line shows how much total variance is explained as you add more components. When it flattens, additional components add little information.',
      'Top features for each component show which card attributes drive that axis of variation — useful for understanding what fundamentally differentiates cards.',
    ],
  },
  {
    id: 'track-record-scatter',
    page: 'Track Record',
    title: 'Predicted vs actual scatter',
    summary: 'Visual comparison of model fair values against real market prices for up to 200 top cards.',
    details: [
      'Each dot is one card. X-axis = actual market price, Y-axis = model\'s fair value estimate. Up to 200 cards are shown, sorted by market price.',
      'The dashed diagonal line represents perfect prediction (predicted = actual). Points above the line are undervalued (model thinks they\'re worth more than market); points below are overvalued.',
      'Green dots: cards flagged as undervalued (model fair > market × 1.25). Blue dots: fairly valued (within 25% of each other). Red dots: overvalued (market > model fair × 1.25).',
      'A tight cluster along the diagonal means high overall model accuracy. Scatter spread indicates disagreement between model and market.',
      'The summary line above the chart shows counts of undervalued, fair, and overvalued cards in the current data set.',
    ],
  },
]
